// Code generated by MockGen. DO NOT EDIT.
// Source: finder.go

// Package markup is a generated GoMock package.
package markup

import (
	reflect "reflect"

	plumbing "github.com/go-git/go-git/v5/plumbing"
	gomock "github.com/golang/mock/gomock"
)

// MockFinder is a mock of Finder interface.
type MockFinder struct {
	ctrl     *gomock.Controller
	recorder *MockFinderMockRecorder
}

// MockFinderMockRecorder is the mock recorder for MockFinder.
type MockFinderMockRecorder struct {
	mock *MockFinder
}

// NewMockFinder creates a new mock instance.
func NewMockFinder(ctrl *gomock.Controller) *MockFinder {
	mock := &MockFinder{ctrl: ctrl}
	mock.recorder = &MockFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinder) EXPECT() *MockFinderMockRecorder {
	return m.recorder
}

// FindSHAs mocks base method.
func (m *MockFinder) FindSHAs(arg0 string) ([]plumbing.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSHAs", arg0)
	ret0, _ := ret[0].([]plumbing.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSHAs indicates an expected call of FindSHAs.
func (mr *MockFinderMockRecorder) FindSHAs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSHAs", reflect.TypeOf((*MockFinder)(nil).FindSHAs), arg0)
}
