name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build
        run: go build

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Run unit tests
        run: go test ./... -coverprofile cover.out

      - name: Upload the coverage to Codecov
        uses: codecov/codecov-action@v4
